version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: masterkinder-backend
    ports:
      - "8080:80" # Mappa API-porten från containern (80) till värdmaskinens port (8080)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultSQLConnection=Server=db;Database=MasterKinder;User=sa;Password=Your_password123;
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # SQL Server körs på standardporten för SQL (1433)
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
